env:
  # Disable CGO for now. This means binaries won't be able to run
  # "infra server" until we enable CGO at a later time.
  # TODO (https://github.com/infrahq/infra/issues/65)
  - CGO_ENABLED=0
  - GO111MODULE=on
project_name: infra
builds:
  - id: infra
    ldflags:
      - -s
      - -w
      - -X github.com/infrahq/infra/internal.Branch={{ .Branch }}
      - -X github.com/infrahq/infra/internal.Version={{ .Version }}
      - -X github.com/infrahq/infra/internal.Commit={{ .FullCommit }}
      - -X github.com/infrahq/infra/internal.Date={{ .Date }}
    binary: infra
    main: ./main.go
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
nfpms:
  - id: packages
    package_name: infra
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - infra
    vendor: Infra Technologies, Inc.
    homepage: https://infrahq.com
    maintainer: Infra Technologies, Inc. <contact@infrahq.com>
    license: Elastic License v2.0
    formats:
      - deb
      - rpm
    bindir: /usr/local/sbin
    contents:
      - src: package-files/systemd/infra.service
        dst: /lib/systemd/system/infra.service
        type: config
      - src: package-files/connector.example.yaml
        dst: /etc/infra/connector.example.yaml
        type: config
      - src: package-files/selinux/infra.pp
        dst: /usr/share/infra/selinux/infra.pp
        type: config
        packager: rpm
    scripts:
      preinstall: package-files/preinstall.sh
      postinstall: package-files/postinstall.sh
      preremove: package-files/preremove.sh
    overrides:
      deb:
        dependencies:
          - passwd
          - procps
        suggests:
          - openssh-client
          - openssh-server
      rpm:
        dependencies:
          - shadow-utils
          - procps-ng
        suggests:
          - openssh-clients
          - openssh-server
archives:
  - id: zip
    format: zip
    replacements:
      amd64: x86_64
    files:
      - none*
brews:
  - tap:
      owner: infrahq
      name: homebrew-tap
    commit_author:
      name: infra-ci
      email: contact@infrahq.com
    homepage: https://infrahq.com
    description: Infra
    url_template: "https://github.com/infrahq/infra/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    install: |
      bin.install "infra"
      output = Utils.popen_read("#{bin}/infra completion bash")
      (bash_completion/"infra").write output
      output = Utils.popen_read("#{bin}/infra completion zsh")
      (zsh_completion/"_infra").write output
      output = Utils.popen_read("#{bin}/infra completion fish")
      (fish_completion/"infra.fish").write output
scoop:
  bucket:
    owner: infrahq
    name: scoop
  commit_author:
    name: infra-ci
    email: contact@infrahq.com
  homepage: https://infrahq.com
  description: Infra
  url_template: "https://github.com/infrahq/infra/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
publishers:
  - name: gemfury
    ids: [packages]
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.GEMFURY_TOKEN }}@push.fury.io/infrahq/
checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
snapshot:
  name_template: "{{ .Env.RELEASE_NAME }}"
before:
  hooks:
    - sh -c '
        command -v checkmodule >/dev/null
          && command -v semodule_package >/dev/null
          && checkmodule -M -m -o package-files/selinux/infra.mod package-files/selinux/infra.te
          && semodule_package -o package-files/selinux/infra.pp -m package-files/selinux/infra.mod
          || true
      '
